### Stage1 V2 fastest precision-preserving baseline for RTX 5090

### model
model_name_or_path: ./models/Qwen3-VL-8B-Instruct
trust_remote_code: true
flash_attn: sdpa

### method
stage: sft
do_train: true
finetuning_type: lora
create_new_adapter: true
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all
freeze_vision_tower: false
additional_target: visual.merger
freeze_multi_modal_projector: false
freeze_language_model: false

### dataset
dataset_dir: data/annotation_v4
media_dir: data
dataset: fundus_stage1_en_cot_replay_calibration_train
template: qwen3_vl_nothink
cutoff_len: 2304
overwrite_cache: false
preprocessing_num_workers: 24
tokenized_path: saves/qwen3-vl-8b-fundus/dataset/stage1_en_cot_v2_single_stage
dataloader_num_workers: 4

### qwen3-vl image tokens
image_max_pixels: 589824
image_min_pixels: 65536

### output
output_dir: saves/qwen3-vl-8b-fundus/lora/stage1_en_cot_v2_single_stage_projector
logging_steps: 10
save_steps: 300
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 3.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.04
bf16: true
fp16: false
gradient_checkpointing: true
eval_strategy: "no"
save_strategy: steps
load_best_model_at_end: false
max_grad_norm: 1.0
optim: adamw_torch
ddp_timeout: 180000000
