### model
model_name_or_path: ./models/Qwen3-VL-8B-Instruct
trust_remote_code: true
flash_attn: sdpa

### method
stage: sft
do_train: true
finetuning_type: lora
create_new_adapter: true
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all
freeze_vision_tower: false
freeze_multi_modal_projector: false
freeze_language_model: false

### dataset
dataset_dir: data/annotation
media_dir: data
dataset: fundus_stage1_pilot
template: qwen3_vl_nothink
cutoff_len: 2304
max_samples: 3000
preprocessing_num_workers: 4
dataloader_num_workers: 0
overwrite_cache: true

### qwen3-vl image tokens
image_max_pixels: 262144
image_min_pixels: 65536

### output
output_dir: saves/qwen3-vl-8b-fundus/lora/stage1_pilot
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 8.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
fp16: false
max_grad_norm: 1.0
optim: adamw_torch
gradient_checkpointing: true
ddp_timeout: 180000000
